FROM  phpmyadmin/phpmyadmin
# RUN apt update
# RUN apt install -y wget
# RUN wget -P Downloads https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
# RUN tar -xzf Downloads/phpMyAdmin-latest-all-languages.tar.gz -C /var/www/html
# RUN rm Downloads/phpMyAdmin-latest-all-languages.tar.gz