version: '3.7'

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.99.0/24

services:
  nginx:
    container_name: nginx
    image: nginx_image
    # build: requirements/nginx
    networks:
      inception:
          ipv4_address: 10.12.99.3
    ports:
      - 443:443
    restart: on-failure
    volumes:
      # - ~/Desktop/data/wordpress:/var/www/html/:rw
      - /home/babdelka/data/wordpress:/var/www/html:rw
  wordpress:
    container_name: wordpress
    image: wordpress_image
    # build: requirements/wordpress
    restart: on-failure
    networks:
      inception:
          ipv4_address: 10.12.99.2
    ports:
      - 9000:9000
    volumes:
      # - ~/Desktop/data/wordpress:/var/www/html/:rw
      - /home/babdelka/data/wordpress:/var/www/html/:rw
  mariadb:
    container_name: mariadb
    image: mariadb_image
    # build: requirements/mariadb
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    # image: mariadb:latest
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      # - ~/Desktop/data/db:/var/lib/mysql:rw
      - /home/babdelka/data/db:/var/lib/mysql:rw
    env_file:
      - .env
    # command: mysqld_safe
    networks:
      inception:
          ipv4_address: 10.12.99.4
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    # build: requirements/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=10.12.99.4
      - PMA_PORT=3306
    ports:
      - 8080:80
    networks:
      inception:
          ipv4_address: 10.12.99.5
    


