version: '3.7'

volumes:
  wordpress:
     driver_opts:
       type: none
       o: bind
       device: /home/babdelka/data/wordpress
  mariadb:
     driver_opts:
       type: none
       o: bind
       device: /home/babdelka/data/db
  grafana:
     driver_opts:
       type: none
       o: bind
       device: /home/babdelka/data/grafana
  bonuss_site:
     driver_opts:
       type: none
       o: bind
       device: /home/babdelka/data/bonus

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.99.0/24

services:
  nginx:
    container_name: nginx
    image: nginx
    networks:
      inception:
          ipv4_address: 10.12.99.3
    ports:
      - 443:443
    restart: on-failure
    volumes:
      - wordpress:/var/www/html:rw
      - bonuss_site:/var/www/htmlbonus:rw
  wordpress:
    hostname: wordpress
    container_name: wordpress
    image: wordpress
    restart: on-failure
    networks:
      inception:
          ipv4_address: 10.12.99.2
    expose:
      - 9000
      - 9100
    volumes:
      - wordpress:/var/www/html:rw
  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb
    restart: on-failure
    expose:
      - 3306
      - 9100
    volumes:
      - mariadb:/var/lib/mysql:rw
    env_file:
      - .env
    networks:
      inception:
          ipv4_address: 10.12.99.4
  grafana:
    cap_add:
      - ALL
    container_name: grafana
    image: grafana
    restart: on-failure
    ports:
      - 3000:3000
    expose:
      - 9100
    volumes:
      - grafana:/grafana:rw
    networks:
      inception:
          ipv4_address: 10.12.99.5
  redis:
    container_name: redis
    image: redis
    restart: on-failure
    expose:
      - 6379
    networks:
      inception:
          ipv4_address: 10.12.99.6
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 8080:443
    networks:
      inception:
          ipv4_address: 10.12.99.7
  ftp:
    container_name: ftp
    image: ftp
    restart: on-failure
    ports:
      - 21:21
      - 20:20
    environment:
      - NEWUSER=$NEWUSER
      - NEWUSER_PASSWORD=$NEWUSER_PASSWORD 
    volumes:
      - wordpress:/wp/:rw
    networks:
      inception:
          ipv4_address: 10.12.99.8