version: '3.7'

networks:
  inception:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.99.0/24

volumes:
  # Wordpress:
  DB:

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      inception:
          ipv4_address: 10.12.99.3
    ports:
      - 443:443
    restart: always
    volumes:
      - /home/babdelka/data/wordpress:/var/www/html:rw
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    networks:
      inception:
          ipv4_address: 10.12.99.2
    ports:
      - 9000:9000
    volumes:
      - /home/babdelka/data/wordpress:/var/www/html/:rw
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    # image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/babdelka/data/db:/var/lib/mysql
    env_file:
      - .env
    # command: mysqld_safe
    networks:
      inception:
          ipv4_address: 10.12.99.4
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=10.12.99.4
      - PMA_PORT=3306
    networks:
      inception:
          ipv4_address: 10.12.99.5


